serviceAccount: 'projects/$PROJECT_ID/serviceAccounts/t2x-cloudbuild@$PROJECT_ID.iam.gserviceaccount.com'

options:
  automapSubstitutions: true
  dynamicSubstitutions: true
  logging: 'LEGACY'
  defaultLogsBucketBehavior: 'REGIONAL_USER_OWNED_BUCKET'

substitutions:
  _API_DOCKER_IMAGE: 'us-central1-docker.pkg.dev/${PROJECT_ID}/talk-to-docs/t2x-api'
  _UI_DOCKER_IMAGE: 'us-central1-docker.pkg.dev/${PROJECT_ID}/talk-to-docs/t2x-ui'
  # _RUN_TYPE will be 'plan' by default. Override with 'apply' to apply changes.
  _RUN_TYPE: 'plan'

steps:
- id: tree
  name: 'alpine'
  script: apk add --no-cache tree && echo "" && tree -a && echo ""

- id: build_api
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_API_DOCKER_IMAGE}:latest', '-t', '${_API_DOCKER_IMAGE}:${BUILD_ID}', '-f', 'Dockerfile.api', '.']

- id: push_api
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', '--all-tags', '${_API_DOCKER_IMAGE}']

- id: build_ui
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_UI_DOCKER_IMAGE}:latest', '-t', '${_UI_DOCKER_IMAGE}:${BUILD_ID}', '-f' , 'Dockerfile.ui', '.']

- id: push_ui
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', '--all-tags', '${_UI_DOCKER_IMAGE}']

- id: init
  name: 'hashicorp/terraform:latest'
  dir: 'terraform/main'
  script: |
    ### Uncomment the following block to enable dynamic backend configuration.
    # echo ""
    # echo "Set the Remote State Bucket Name for the current project. Processing backend_template.hcl..."
    # sed "s/^ *bucket = .*/    bucket = \"terraform-state-${PROJECT_ID}\"/g" backend_template.hcl > terraform_backend.tf
    # echo ""
    # echo "terraform_backend.tf content:"
    # echo '```hcl'
    # cat terraform_backend.tf
    # echo '```'
    ### End dynamic backend configuration block.
    echo ""
    terraform init -reconfigure
    echo ""
    echo "Terraform version:"
    echo ""
    terraform version
    echo ""
    echo "Terraform workspace: $(terraform workspace list)"
    echo ""

- id: validate
  name: 'hashicorp/terraform:latest'
  dir: 'terraform/main'
  args: ['validate']

# Display the format diff. Don't write changes.
- id: fmt
  name: 'hashicorp/terraform:latest'
  dir: 'terraform/main'
  args: ['fmt', '-recursive', '-diff', '-write=false']

- id: plan
  name: 'hashicorp/terraform:latest'
  dir: 'terraform/main'
  env:
    - TF_VAR_docker_image={t2x-api="${_API_DOCKER_IMAGE}:${BUILD_ID}", t2x-ui="${_UI_DOCKER_IMAGE}:${BUILD_ID}"}
  args: ['plan', '-input=false', '-out', '.terraform/tfplan']

- id: apply
  name: 'hashicorp/terraform:latest'
  dir: 'terraform/main'
  script: |
    echo ""
    echo "Detected '_RUN_TYPE' value: '${_RUN_TYPE}'"
    echo ""
    if [ "${_RUN_TYPE}" = "apply" ]; then
      terraform apply -auto-approve -input=false .terraform/tfplan
    else
      echo "'_RUN_TYPE' substitution override not received. Defaulting to plan-only and skipping apply"
    fi
    echo ""
