docx_chunking: custom
xml_extraction: custom2
json_chunking: custom
pdf_extraction: default
pdf_chunking: default
html_extraction: custom

project_id: null
dataset_id: dataset
table_name: parsing_table
data_store_id: data_store_id

bucket_parse_interval: 600