name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Authenticate with Google Cloud
      uses: 'google-github-actions/auth@v2'
      with:
        project_id: 'chertushkin-genai-sa'
        workload_identity_provider: '${{ secrets.WORKLOAD_IDENTITY_POOL }}'

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pylint pytest
        pip install -e .

    - name: Lint with pylint
      run: |
        # stop the build if there are Python syntax errors or undefined names
        pylint gen_ai/llm.py gen_ai/common gen_ai/deploy gen_ai/check_pipeline.py

    - name: Create directory structure in writable area
      run: mkdir -p $HOME/resources/uhg/main_folder

    - name: Create symlink
      run: |
        sudo ln -s $HOME/resources /mnt/resources
        echo "Directory structure created and symlinked"

    - name: Test with pytest
      run: |
        gsutil ls gs://public_ci_cd_bucket
        python gen_ai/copy_resources.py gs://public_ci_cd_bucket
        pytest gen_ai/tests
